version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  jobs:
    build:
      html:
        - bash docs/build.sh $READTHEDOCS_OUTPUT/html

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
