version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - jq
  jobs:
    build:
      html:
        - bash -c "export HEADAS=$(conda env list --json | jq -r '.envs[-1]')/heasoft; source \$HEADAS/headas-init.sh;"
        - bash -c 'export env_path=$(conda env list --json | jq -r ".envs[-1]"); source $env_path/heasoft/headas-init.sh; echo $HEADAS'
#        - bash -c 'source ~/.bashrc && bash docs/build.sh $READTHEDOCS_OUTPUT/html'

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
