version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
     - sphinx-apidoc -e -o docs/apidoc src/elisa

sphinx:
  configuration: docs/conf.py
  # fail_on_warning: true

# formats:
#   - pdf
#   - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs