version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  jobs:
    pre_install:
      - export HEADAS=$CONDA_PREFIX/heasoft
      - . $HEADAS/headas.sh
    pre_build:
      - sphinx-apidoc -e -T --templatedir docs/_templates/apidoc -o docs/apidoc src/elisa

conda:
  environment: docs/environment.yml

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - xspec

# formats:
#   - pdf
#   - epub
