version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - jq
  jobs:
    build:
      html:
        - conda info --json | jq -r '.default_prefix'
        - bash -c "export HEADAS=$(conda info --json | jq -r '.default_prefix')/heasoft; source \$HEADAS/headas-init.sh; which xspec; pip list"
#        - bash -c 'source ~/.bashrc && bash docs/build.sh $READTHEDOCS_OUTPUT/html'

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
