version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  apt_packages:
    - jq
  jobs:
    build:
      html:
        - conda env list --json
        - echo "export HEADAS=$(conda env list --json | jq -r '.envs[-1]')" >> ~/.bashrc
        - echo 'source $HEADAS/headas-init.sh' >> ~/.bashrc
        - bash -c 'echo $HEADAS'
        - bash -c 'which xspec'
        - bash -c 'source ~/.bashrc && which xspec'
        - bash -c 'source ~/.bashrc && python -c "import xspex"'
#        - bash -c 'source ~/.bashrc && bash docs/build.sh $READTHEDOCS_OUTPUT/html'

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
