version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  jobs:
    pre_build:
      - bash -c "echo $CONDA_PREFIX"
    build:
      html:
        - bash -c "bash docs/build.sh $READTHEDOCS_OUTPUT/html"

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
