version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  jobs:
    pre_install:
      - conda env list
      - conda list
    pre_build:
      - sphinx-apidoc -e -T --templatedir docs/_templates/apidoc -o docs/apidoc src/elisa

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: docs/environment.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - xspec

# formats:
#   - pdf
#   - epub
