version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "miniconda-latest"
  jobs:
    build:
      html:
        - conda init
        - bash -c "source ~/.bashrc && echo $HEADAS"
        - bash -c "source ~/.bashrc && bash docs/build.sh $READTHEDOCS_OUTPUT/html"

conda:
  environment: docs/environment.yml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true
